# Generated by Django 3.0.2 on 2020-01-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riderequests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='allow_strangers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='driver',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='request',
            name='n_passengers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='request',
            name='other_user_passengers',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('O', 'open'), ('C', 'confirmed'), ('F', 'completed')], default='O', max_length=1),
        ),
    ]
