# Generated by Django 3.0.2 on 2020-02-06 20:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riderequests', '0002_auto_20200120_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owner',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='license_plate_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='max_capacity',
            field=models.IntegerField(blank=True, default=4),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='special_features',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_brand',
            field=models.CharField(choices=[('H', 'honda'), ('F', 'ferrari'), ('L', 'lexus')], default='H', max_length=2),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type_registered',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='request sent time'),
        ),
    ]
