# Generated by Django 3.0.2 on 2020-02-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riderequests', '0004_remove_vehicle_vehicle_type_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='special_features',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='request',
            name='vehicle_brand',
            field=models.CharField(blank=True, choices=[('H', 'honda'), ('F', 'ferrari'), ('L', 'lexus')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='max_capacity',
            field=models.IntegerField(default=4),
        ),
    ]
