# Generated by Django 3.0.2 on 2020-01-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.CharField(max_length=50)),
                ('arrive_time', models.DateTimeField(verbose_name='expected arrival')),
                ('request_time', models.DateTimeField(verbose_name='request sent time')),
                ('src_loc', models.CharField(max_length=500)),
                ('dst_loc', models.CharField(max_length=500)),
            ],
        ),
    ]
