# Generated by Django 3.0.2 on 2020-02-06 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riderequests', '0003_auto_20200206_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type_registered',
        ),
    ]
