# Generated by Django 3.0.2 on 2020-02-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riderequests', '0005_auto_20200206_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='license_plate',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
